sudo: false
language: node_js
install:
  - npm install -g bower web-component-tester
  - bower install
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
  - wct
